In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("train.csv")
df.head()

                 Id  Target
0  b180fa8a0b604252       3
1  84cf96a988f64aee       0
2  bf02300f7edd4b01       2
3  df0453503f794e60       3
4  883a297a06db4160       0

In [5]:
df.groupby("Target").count()

        Id
Target
0       22
1       13
2       28
3       29
4        8